"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Appointment, cancelAppointment, getAppointments } from "@/lib/patient-portal";

export default function AppointmentsPage() {
  const [appointments, setAppointments] = useState<Appointment[]>([]);
  useEffect(() => { const load = () => setAppointments(getAppointments()); load(); window.addEventListener("ruralcare:appointments-changed", load); return () => window.removeEventListener("ruralcare:appointments-changed", load); }, []);
  const cancel = (id: string) => { cancelAppointment(id); setAppointments(getAppointments()); };
  return <main className="mx-auto w-full max-w-5xl p-4 sm:p-8"><div className="mb-6 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h1 className="text-3xl font-bold text-on-surface">My appointments</h1><p className="mt-1 text-on-surface-variant">Your confirmed and cancelled consultation bookings.</p></div><Link href="/find-doctor" className="rounded-lg bg-primary px-5 py-3 text-center font-semibold text-on-primary">Book appointment</Link></div>{appointments.length ? <div className="space-y-4">{appointments.map((appointment) => <article key={appointment.id} className="flex flex-col justify-between gap-4 rounded-xl border border-outline-variant bg-surface-container-lowest p-5 shadow-sm sm:flex-row sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-bold text-on-surface">{appointment.doctorName}</h2><span className={`rounded-full px-2 py-1 text-xs font-bold ${appointment.status === "confirmed" ? "bg-tertiary-fixed text-on-tertiary-fixed-variant" : "bg-surface-container text-on-surface-variant"}`}>{appointment.status}</span></div><p className="mt-1 text-primary">{appointment.specialty}</p><p className="mt-2 text-sm text-on-surface-variant">{appointment.date} at {appointment.time} · {appointment.mode === "audio" ? "Audio-only consultation" : "Video consultation"}</p></div>{appointment.status === "confirmed" && <button onClick={() => cancel(appointment.id)} className="rounded-lg border border-error px-4 py-2 font-semibold text-error hover:bg-error-container">Cancel appointment</button>}</article>)}</div> : <div className="rounded-xl border border-dashed border-outline-variant p-10 text-center"><span className="material-symbols-outlined text-4xl text-primary">calendar_month</span><h2 className="mt-3 text-xl font-bold text-on-surface">No appointments yet</h2><p className="mt-1 text-on-surface-variant">Book a consultation with a verified doctor to get started.</p><Link href="/find-doctor" className="mt-5 inline-block rounded-lg bg-primary px-5 py-3 font-semibold text-on-primary">Find doctors</Link></div>}</main>;
}
