from datetime import date, datetime, timezone
from typing import Optional

from bson import ObjectId
from fastapi import APIRouter, Depends, HTTPException, Query, status
from pymongo.errors import DuplicateKeyError

from backend.api.deps import (
    get_current_user,
    require_doctor,
    require_patient,
)
from backend.core.database import get_database
from backend.models.appointment import AppointmentModel
from backend.models.patient import PatientModel
from backend.schemas.appointment import (
    AppointmentCreate,
    AppointmentListResponse,
    AppointmentResponse,
    AppointmentStatus,
    AppointmentUpdate,
)
from backend.schemas.user import UserResponse


router = APIRouter()


ACTIVE_STATUSES = {
    "pending",
    "confirmed",
    "rescheduled",
}


def serialize_appointment(
    appointment: dict,
    doctor: Optional[dict] = None,
) -> dict:
    result = dict(appointment)

    result["id"] = str(result.pop("_id"))

    if doctor:
        result["doctor_name"] = doctor.get("name")
        result["doctor_specialization"] = doctor.get(
            "specialization"
        )
        result["consultation_fee"] = doctor.get(
            "consultation_fee"
        )

    return result


def parse_time(value: str):
    try:
        return datetime.strptime(value, "%H:%M").time()
    except ValueError:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Appointment time must use HH:MM format.",
        )


def get_day_name(appointment_date: date) -> str:
    return appointment_date.strftime("%A").lower()


def availability_allows_slot(
    availability,
    appointment_date: date,
    appointment_time: str,
) -> bool:
    """
    Supports the structured weekly availability generated by
    Module 4 while remaining tolerant of small naming differences.

    Supported examples:

    {
        "monday": {
            "enabled": true,
            "start_time": "09:00",
            "end_time": "17:00"
        }
    }

    or:

    {
        "monday": {
            "enabled": true,
            "start": "09:00",
            "end": "17:00"
        }
    }
    """

    if not availability:
        return False

    day = get_day_name(appointment_date)

    if isinstance(availability, dict):
        day_config = availability.get(day)

        if day_config is None:
            day_config = availability.get(day.capitalize())

        if day_config is None:
            return False

    elif isinstance(availability, list):
        day_config = None

        for item in availability:
            if not isinstance(item, dict):
                continue

            item_day = str(
                item.get("day", "")
            ).lower()

            if item_day == day:
                day_config = item
                break

        if day_config is None:
            return False

    else:
        return False

    if isinstance(day_config, list):
        ranges = day_config
    else:
        ranges = [day_config]

    selected_time = parse_time(appointment_time)

    for period in ranges:
        if not isinstance(period, dict):
            continue

        enabled = period.get("enabled", True)

        if enabled is False:
            continue

        start_value = (
            period.get("start_time")
            or period.get("start")
            or period.get("from")
        )

        end_value = (
            period.get("end_time")
            or period.get("end")
            or period.get("to")
        )

        if not start_value or not end_value:
            continue

        try:
            start_time = datetime.strptime(
                str(start_value),
                "%H:%M",
            ).time()

            end_time = datetime.strptime(
                str(end_value),
                "%H:%M",
            ).time()
        except ValueError:
            continue

        if start_time <= selected_time < end_time:
            return True

    return False


async def get_doctor(doctor_id: str) -> Optional[dict]:
    db = get_database()

    try:
        return await db["doctors"].find_one(
            {"_id": ObjectId(doctor_id)}
        )
    except Exception:
        return None


async def get_patient_for_user(
    user_id: str,
) -> Optional[dict]:
    return await PatientModel.get_by_user_id(user_id)


async def build_response(
    appointment: dict,
) -> AppointmentResponse:
    doctor = await get_doctor(
        appointment["doctor_id"]
    )

    return AppointmentResponse(
        **serialize_appointment(
            appointment,
            doctor,
        )
    )


@router.post(
    "",
    response_model=AppointmentResponse,
    status_code=status.HTTP_201_CREATED,
)
async def create_appointment(
    payload: AppointmentCreate,
    current_user: UserResponse = Depends(require_patient),
):
    patient = await get_patient_for_user(
        current_user.id
    )

    if not patient:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Patient profile not found. Please complete your profile first.",
        )

    doctor = await get_doctor(payload.doctor_id)

    if not doctor:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Doctor not found.",
        )

    if doctor.get("verification_status") != "approved":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="This doctor is not currently available for consultations.",
        )

    if payload.appointment_date < date.today():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Appointment date must be today or a future date.",
        )

    selected_time = parse_time(
        payload.appointment_time
    )

    if payload.appointment_date == date.today():
        now = datetime.now().time()

        if selected_time <= now:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Appointment time must be in the future.",
            )

    if not availability_allows_slot(
        doctor.get("availability"),
        payload.appointment_date,
        payload.appointment_time,
    ):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="The selected time is outside the doctor's availability.",
        )

    patient_id = str(patient["_id"])

    if await AppointmentModel.slot_is_taken(
        doctor_id=payload.doctor_id,
        appointment_date=payload.appointment_date,
        appointment_time=payload.appointment_time,
    ):
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="This appointment slot has already been booked.",
        )

    appointment_data = {
        "patient_id": patient_id,
        "doctor_id": payload.doctor_id,
        "appointment_date": payload.appointment_date,
        "appointment_time": payload.appointment_time,
        "mode": payload.mode.value,
        "reason": payload.reason,
        "status": AppointmentStatus.pending.value,
    }

    try:
        appointment = await AppointmentModel.create(
            appointment_data
        )
    except DuplicateKeyError:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="This appointment slot has already been booked.",
        )

    return await build_response(appointment)


@router.get(
    "",
    response_model=AppointmentListResponse,
)
async def get_appointments(
    current_user: UserResponse = Depends(
        get_current_user
    ),
    appointment_status: Optional[str] = Query(
        default=None,
        alias="status",
    ),
):
    if current_user.role == "patient":
        patient = await get_patient_for_user(
            current_user.id
        )

        if not patient:
            return AppointmentListResponse(
                appointments=[]
            )

        appointments = (
            await AppointmentModel.get_by_patient(
                str(patient["_id"])
            )
        )

    elif current_user.role == "doctor":
        db = get_database()

        doctor = await db["doctors"].find_one(
            {"user_id": current_user.id}
        )

        if not doctor:
            return AppointmentListResponse(
                appointments=[]
            )

        appointments = (
            await AppointmentModel.get_by_doctor(
                str(doctor["_id"])
            )
        )

    else:
        db = get_database()

        cursor = db["appointments"].find({}).sort(
            [
                ("appointment_date", 1),
                ("appointment_time", 1),
            ]
        )

        appointments = await cursor.to_list(
            length=1000
        )

    if appointment_status:
        appointments = [
            item
            for item in appointments
            if item.get("status")
            == appointment_status
        ]

    responses = []

    for appointment in appointments:
        responses.append(
            await build_response(appointment)
        )

    return AppointmentListResponse(
        appointments=responses
    )


@router.get(
    "/me",
    response_model=AppointmentListResponse,
)
async def get_my_appointments(
    current_user: UserResponse = Depends(
        get_current_user
    ),
):
    if current_user.role == "patient":
        patient = await get_patient_for_user(
            current_user.id
        )

        if not patient:
            return AppointmentListResponse(
                appointments=[]
            )

        appointments = (
            await AppointmentModel.get_by_patient(
                str(patient["_id"])
            )
        )

    elif current_user.role == "doctor":
        db = get_database()

        doctor = await db["doctors"].find_one(
            {"user_id": current_user.id}
        )

        if not doctor:
            return AppointmentListResponse(
                appointments=[]
            )

        appointments = (
            await AppointmentModel.get_by_doctor(
                str(doctor["_id"])
            )
        )

    else:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="This endpoint is only available to patients and doctors.",
        )

    responses = []

    for appointment in appointments:
        responses.append(
            await build_response(appointment)
        )

    return AppointmentListResponse(
        appointments=responses
    )


@router.get(
    "/{appointment_id}",
    response_model=AppointmentResponse,
)
async def get_appointment(
    appointment_id: str,
    current_user: UserResponse = Depends(
        get_current_user
    ),
):
    appointment = await AppointmentModel.get_by_id(
        appointment_id
    )

    if not appointment:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Appointment not found.",
        )

    allowed = False

    if current_user.role == "admin":
        allowed = True

    elif current_user.role == "patient":
        patient = await get_patient_for_user(
            current_user.id
        )

        allowed = bool(
            patient
            and appointment["patient_id"]
            == str(patient["_id"])
        )

    elif current_user.role == "doctor":
        db = get_database()

        doctor = await db["doctors"].find_one(
            {"user_id": current_user.id}
        )

        allowed = bool(
            doctor
            and appointment["doctor_id"]
            == str(doctor["_id"])
        )

    if not allowed:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You are not allowed to access this appointment.",
        )

    return await build_response(appointment)


@router.put(
    "/{appointment_id}",
    response_model=AppointmentResponse,
)
async def update_appointment(
    appointment_id: str,
    payload: AppointmentUpdate,
    current_user: UserResponse = Depends(
        get_current_user
    ),
):
    appointment = await AppointmentModel.get_by_id(
        appointment_id
    )

    if not appointment:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Appointment not found.",
        )

    db = get_database()

    doctor = await get_doctor(
        appointment["doctor_id"]
    )

    patient = await get_patient_for_user(
        current_user.id
    )

    is_patient = bool(
        current_user.role == "patient"
        and patient
        and appointment["patient_id"]
        == str(patient["_id"])
    )

    is_doctor = bool(
        current_user.role == "doctor"
        and doctor
        and doctor.get("user_id")
        == current_user.id
    )

    if not is_patient and not is_doctor and current_user.role != "admin":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You are not allowed to modify this appointment.",
        )

    update_data = payload.model_dump(
        exclude_unset=True
    )

    requested_status = update_data.get("status")

    if requested_status:
        if is_patient and requested_status not in {
            AppointmentStatus.cancelled.value,
            AppointmentStatus.rescheduled.value,
        }:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Patients can only cancel or request rescheduling.",
            )

        if is_doctor and requested_status not in {
            AppointmentStatus.confirmed.value,
            AppointmentStatus.completed.value,
            AppointmentStatus.cancelled.value,
            AppointmentStatus.rescheduled.value,
        }:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Invalid doctor appointment status.",
            )

    new_date = update_data.get(
        "appointment_date",
        appointment["appointment_date"],
    )

    new_time = update_data.get(
        "appointment_time",
        appointment["appointment_time"],
    )

    if "appointment_date" in update_data or "appointment_time" in update_data:
        if not is_patient and current_user.role != "admin":
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Only the patient can request a new appointment slot.",
            )

        if new_date < date.today():
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Appointment date must be today or later.",
            )

        if not availability_allows_slot(
            doctor.get("availability") if doctor else None,
            new_date,
            new_time,
        ):
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="The selected time is outside the doctor's availability.",
            )

        if await AppointmentModel.slot_is_taken(
            doctor_id=appointment["doctor_id"],
            appointment_date=new_date,
            appointment_time=new_time,
            exclude_id=appointment_id,
        ):
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail="The requested appointment slot is already booked.",
            )

        update_data["status"] = (
            AppointmentStatus.rescheduled.value
        )

    if (
        requested_status
        == AppointmentStatus.cancelled.value
        and appointment["status"]
        == AppointmentStatus.completed.value
    ):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="A completed appointment cannot be cancelled.",
        )

    if not update_data:
        return await build_response(appointment)

    try:
        updated = await AppointmentModel.update(
            appointment_id,
            update_data,
        )
    except DuplicateKeyError:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="The requested appointment slot is already booked.",
        )

    if not updated:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Appointment not found.",
        )

    return await build_response(updated)


@router.put(
    "/{appointment_id}/cancel",
    response_model=AppointmentResponse,
)
async def cancel_appointment(
    appointment_id: str,
    current_user: UserResponse = Depends(
        get_current_user
    ),
):
    appointment = await AppointmentModel.get_by_id(
        appointment_id
    )

    if not appointment:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Appointment not found.",
        )

    patient = await get_patient_for_user(
        current_user.id
    )

    allowed = bool(
        current_user.role == "patient"
        and patient
        and appointment["patient_id"]
        == str(patient["_id"])
    )

    if current_user.role == "doctor":
        doctor = await get_doctor(
            appointment["doctor_id"]
        )
        allowed = bool(
            doctor
            and doctor.get("user_id")
            == current_user.id
        )

    if current_user.role == "admin":
        allowed = True

    if not allowed:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You are not allowed to cancel this appointment.",
        )

    if appointment["status"] == "completed":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="A completed appointment cannot be cancelled.",
        )

    updated = await AppointmentModel.update(
        appointment_id,
        {
            "status": AppointmentStatus.cancelled.value
        },
    )

    return await build_response(updated)


@router.put(
    "/{appointment_id}/complete",
    response_model=AppointmentResponse,
)
async def complete_appointment(
    appointment_id: str,
    current_user: UserResponse = Depends(
        require_doctor
    ),
):
    appointment = await AppointmentModel.get_by_id(
        appointment_id
    )

    if not appointment:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Appointment not found.",
        )

    doctor = await get_doctor(
        appointment["doctor_id"]
    )

    if not doctor or doctor.get("user_id") != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You are not allowed to complete this appointment.",
        )

    if appointment["status"] == "cancelled":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="A cancelled appointment cannot be completed.",
        )

    updated = await AppointmentModel.update(
        appointment_id,
        {
            "status": AppointmentStatus.completed.value
        },
    )

    return await build_response(updated)


@router.delete(
    "/{appointment_id}",
    status_code=status.HTTP_204_NO_CONTENT,
)
async def delete_appointment(
    appointment_id: str,
    current_user: UserResponse = Depends(
        get_current_user
    ),
):
    appointment = await AppointmentModel.get_by_id(
        appointment_id
    )

    if not appointment:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Appointment not found.",
        )

    patient = await get_patient_for_user(
        current_user.id
    )

    allowed = bool(
        current_user.role == "patient"
        and patient
        and appointment["patient_id"]
        == str(patient["_id"])
    )

    if current_user.role == "admin":
        allowed = True

    if not allowed:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You are not allowed to delete this appointment.",
        )

    if appointment["status"] != "cancelled":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Only cancelled appointments can be deleted.",
        )

    await AppointmentModel.delete(
        appointment_id
    )
